apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  creationTimestamp: null
  name: vm-test-12
  labels:
    kubevirt.io/vm: vm-test-12
    vm.kubevirt.io/template: fedora-desktop-small-with-rules
    vm.kubevirt.io/template.namespace: default
spec:
  running: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vm: vm-test-12
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          interfaces:
          - name: default
            bridge: {}
        machine:
          type: "q35"
        resources:
          requests:
            memory: 128M
      networks:
      - name: default
        pod: {}
      evictionStrategy: LiveMigrate
      terminationGracePeriodSeconds: 0
status: {}
