---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: vmtemplate-admission
webhooks:
  - name: vmtemplate-admission.kubevirt.io
    clientConfig:
      service:
        name: vmtemplate-admission
        namespace: kubevirt
        path: "/"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["kubevirt.io"]
        apiVersions: ["v1alpha3"]
        resources: ["virtualmachines"]
    failurePolicy: Ignore

